services:

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: project-backend-full
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: project-frontend-full
    ports:
      - "443:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules