services:
  postgres:
    image: postgres:16-alpine
    container_name: project-postgres-local
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localpass
      POSTGRES_DB: migration_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    image: redis:7-alpine
    container_name: project-redis-local
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data_local:/data

volumes:
  postgres_data_local:
  redis_data_local:

  