services:

  database:
    image: postgres:16-alpine
    container_name: postgres_db
    env_file: ./database/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5440:5432"
    volumes:
      - ./database/backup_v6.sql:/docker-entrypoint-initdb.d/1_backup_v6.sql
      - ./database/backup_v7.sql:/docker-entrypoint-initdb.d/2_backup_v7.sql
      - postgres_data:/var/lib/postgresql/data

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: project-backend-dev
    env_file: ./backend/.env
    environment:
      - DB_HOST=database
      - DB_PORT=5432
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: project-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  ngrok:
    image: ngrok/ngrok:latest
    container_name: project-ngrok-tunnel
    restart: always
    environment:
      # You can put NGROK_AUTHTOKEN inside a .env file or export it locally
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "frontend:5173"
      - "--url=nonhabitably-arabinosic-dedra.ngrok-free.dev"
    ports:
      - "4040:4040"
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
