name: Deploy Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Current Branch
        run: git branch

      - name: Show Files
        run: ls -la

      - name: Print Message
        run: echo "Pipeline triggered from DEV branch"
