services:
  database:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5440:5432"
    volumes:
      - ./backup_v6.sql:/docker-entrypoint-initdb.d/1_backup_v6.sql
      - ./backup_v7.sql:/docker-entrypoint-initdb.d/2_backup_v7.sql
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

