name: My First Pipeline

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Message
        run: echo "Hello from GitHub Actions"

      - name: Show Current Date
        run: date

      - name: List Repository Files
        run: ls -la
