name: Deploy Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show current branch
        run: git branch

      - name: Show files
        run: ls -la

      
      # Python Setup
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create Backend .env
        run: |
          cat > backend/.env << EOF
          DB_HOST=${{ secrets.DB_HOST }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_PORT=${{ secrets.DB_PORT }}
          
          REDIS_HOST=${{ secrets.REDIS_HOST }}
          REDIS_PORT=${{ secrets.REDIS_PORT }}
          REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
          
          SMTP_HOST=${{ secrets.SMTP_HOST }}
          SMTP_USER=${{ secrets.SMTP_USER }}
          SMTP_PASS=${{ secrets.SMTP_PASS }}
          SMTP_FROM=${{ secrets.SMTP_FROM }}
          TEAM_EMAILS=${{ secrets.TEAM_EMAILS }}
          EOF

      - name: Verify Backend Env
        run: |
          ls -la backend/.env

      - name: Create Zoho .env
        run: |
          cat > zoho-api-integration/.env << EOF
          ZOHO_CLIENT_ID=${{ secrets.ZOHO_CLIENT_ID }}
          ZOHO_CLIENT_SECRET=${{ secrets.ZOHO_CLIENT_SECRET }}
          ZOHO_REFRESH_TOKEN=${{ secrets.ZOHO_REFRESH_TOKEN }}

          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          EOF

      - name: Verify Zoho Env
        run: |
          ls -la zoho-api-integration/.env

      - name: Install Backend Dependencies
        run: |
          cd backend
          pip install -r requirements.txt
      
      # Node Setup
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      - name: Build Backend Docker Image
        run: |
          docker build \
            -t utiliza-backend:latest \
            -f backend/Dockerfile.prod .

      - name: Build Frontend Docker Image
        run: |
          docker build \
            -t utiliza-frontend:latest \
            -f frontend/Dockerfile.prod \
            frontend
      
      - name: Tag Backend Image For ECR
        run: |
           docker tag utiliza-backend:latest \
           ${{ secrets.ECR_BACKEND_REPO }}:latest    

      - name: Tag Frontend Image For ECR
        run: |
          docker tag utiliza-frontend:latest \
          ${{ secrets.ECR_FRONTEND_REPO }}:latest

      - name: Push Backend Image
        run: |
          docker push ${{ secrets.ECR_BACKEND_REPO }}:latest

      - name: Push Frontend Image
        run: |
          docker push ${{ secrets.ECR_FRONTEND_REPO }}:latest

          
      - name: List Docker Images
        run: |
          docker images | grep utiliza

      - name: Save Backend Image
        run: |
          docker save utiliza-backend:latest \
            -o backend-image.tar

      - name: Save Frontend Image
        run: |
          docker save utiliza-frontend:latest \
            -o frontend-image.tar
     
      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-image
          path: backend-image.tar

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-image
          path: frontend-image.tar
          
     
      
