name: Deploy Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show current branch
        run: git branch

      - name: Show files
        run: ls -la

      
      # Python Setup
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create Backend .env
        run: |
          cat > backend/.env << EOF
          DB_HOST=${{ secrets.DB_HOST }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_PORT=${{ secrets.DB_PORT }}
          
          REDIS_HOST=${{ secrets.REDIS_HOST }}
          REDIS_PORT=${{ secrets.REDIS_PORT }}
          REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
          
          SMTP_HOST=${{ secrets.SMTP_HOST }}
          SMTP_USER=${{ secrets.SMTP_USER }}
          SMTP_PASS=${{ secrets.SMTP_PASS }}
          SMTP_FROM=${{ secrets.SMTP_FROM }}
          TEAM_EMAILS=${{ secrets.TEAM_EMAILS }}
          EOF

      - name: Verify Backend Env
        run: |
          ls -la backend/.env

      - name: Create Zoho .env
        run: |
          cat > zoho-api-integration/.env << EOF
          ZOHO_CLIENT_ID=${{ secrets.ZOHO_CLIENT_ID }}
          ZOHO_CLIENT_SECRET=${{ secrets.ZOHO_CLIENT_SECRET }}
          ZOHO_REFRESH_TOKEN=${{ secrets.ZOHO_REFRESH_TOKEN }}

          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          EOF

      - name: Verify Zoho Env
        run: |
          ls -la zoho-api-integration/.env

      - name: Install Backend Dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Validate Backend
        run: |
          cd backend
          python -c "from app.main import app; print('Backend Loaded Successfully')"

      # Node Setup
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build
     
      
